import { z } from 'zod';
import { ENV_DEFAULTS, LOG_LEVELS, MEDIA_VIDEO_ENCODERS } from './defaults';
import { parseBooleanEnv, parseFloatEnv, parseIntegerEnv } from './parsers';

export const runtimeConfigSchema = z.object({
  NODE_ENV: z.string().default(ENV_DEFAULTS.NODE_ENV),
  LOG: z.enum(LOG_LEVELS).default(ENV_DEFAULTS.LOG),
  PORT: parseIntegerEnv('PORT', ENV_DEFAULTS.PORT, {
    min: 0,
    max: 65535,
  }),

  I18N: z.string().default(ENV_DEFAULTS.I18N),

  API_URL: z.string().url(),
  ADMIN_UI_TOKEN: z.string().default(ENV_DEFAULTS.ADMIN_UI_TOKEN),
  ADMIN_UI_LOCAL_ONLY: parseBooleanEnv(ENV_DEFAULTS.ADMIN_UI_LOCAL_ONLY),

  DISCORD_TOKEN: z.string(),
  DISCORD_CLIENT_ID: z.string(),
  INGEST_API_TOKEN: z.string().default(ENV_DEFAULTS.INGEST_API_TOKEN),

  DATABASE_URL: z.string(),

  HIDE_COMMANDS_DISABLED: z.string().default(ENV_DEFAULTS.HIDE_COMMANDS_DISABLED),
  DEFAULT_DURATION: parseIntegerEnv('DEFAULT_DURATION', ENV_DEFAULTS.DEFAULT_DURATION),
  PLAYBACK_JOB_RETENTION_HOURS: parseIntegerEnv(
    'PLAYBACK_JOB_RETENTION_HOURS',
    ENV_DEFAULTS.PLAYBACK_JOB_RETENTION_HOURS,
  ),

  MEDIA_STORAGE_DIR: z.string().default(ENV_DEFAULTS.MEDIA_STORAGE_DIR),
  MEDIA_CACHE_TTL_HOURS: parseIntegerEnv('MEDIA_CACHE_TTL_HOURS', ENV_DEFAULTS.MEDIA_CACHE_TTL_HOURS),
  MEDIA_CACHE_MAX_TOTAL_MB: parseIntegerEnv('MEDIA_CACHE_MAX_TOTAL_MB', ENV_DEFAULTS.MEDIA_CACHE_MAX_TOTAL_MB),
  MEDIA_BOARD_MAX_TOTAL_MB: parseIntegerEnv('MEDIA_BOARD_MAX_TOTAL_MB', ENV_DEFAULTS.MEDIA_BOARD_MAX_TOTAL_MB),
  MEDIA_DOWNLOAD_TIMEOUT_MS: parseIntegerEnv('MEDIA_DOWNLOAD_TIMEOUT_MS', ENV_DEFAULTS.MEDIA_DOWNLOAD_TIMEOUT_MS),
  MEDIA_MAX_SIZE_MB: parseIntegerEnv('MEDIA_MAX_SIZE_MB', ENV_DEFAULTS.MEDIA_MAX_SIZE_MB),
  MEDIA_VIDEO_MAX_HEIGHT: parseIntegerEnv('MEDIA_VIDEO_MAX_HEIGHT', ENV_DEFAULTS.MEDIA_VIDEO_MAX_HEIGHT),
  MEDIA_VIDEO_ENCODER: z.enum(MEDIA_VIDEO_ENCODERS).default(ENV_DEFAULTS.MEDIA_VIDEO_ENCODER),
  MEDIA_VIDEO_NVENC_PRESET: z.string().default(ENV_DEFAULTS.MEDIA_VIDEO_NVENC_PRESET),
  MEDIA_VIDEO_PRESET: z.string().default(ENV_DEFAULTS.MEDIA_VIDEO_PRESET),
  MEDIA_AUDIO_NORMALIZE_ENABLED: parseBooleanEnv(ENV_DEFAULTS.MEDIA_AUDIO_NORMALIZE_ENABLED),
  MEDIA_AUDIO_LOUDNORM_I: parseFloatEnv('MEDIA_AUDIO_LOUDNORM_I', ENV_DEFAULTS.MEDIA_AUDIO_LOUDNORM_I),
  MEDIA_AUDIO_LOUDNORM_LRA: parseFloatEnv('MEDIA_AUDIO_LOUDNORM_LRA', ENV_DEFAULTS.MEDIA_AUDIO_LOUDNORM_LRA),
  MEDIA_AUDIO_LOUDNORM_TP: parseFloatEnv('MEDIA_AUDIO_LOUDNORM_TP', ENV_DEFAULTS.MEDIA_AUDIO_LOUDNORM_TP),
  TWITTER_OEMBED_ENDPOINT: z.string().url().default(ENV_DEFAULTS.TWITTER_OEMBED_ENDPOINT),
  TWITTER_VIDEO_RESOLVER_BASE_URL: z.string().url().default(ENV_DEFAULTS.TWITTER_VIDEO_RESOLVER_BASE_URL),
  TWITTER_CARD_DURATION_SEC: parseIntegerEnv('TWITTER_CARD_DURATION_SEC', ENV_DEFAULTS.TWITTER_CARD_DURATION_SEC),
  PAIRING_CODE_TTL_MINUTES: parseIntegerEnv('PAIRING_CODE_TTL_MINUTES', ENV_DEFAULTS.PAIRING_CODE_TTL_MINUTES),
  YTDLP_BINARY: z.string().default(ENV_DEFAULTS.YTDLP_BINARY),
  YTDLP_CONCURRENT_FRAGMENTS: parseIntegerEnv('YTDLP_CONCURRENT_FRAGMENTS', ENV_DEFAULTS.YTDLP_CONCURRENT_FRAGMENTS),
  YTDLP_FORMAT: z.string().default(ENV_DEFAULTS.YTDLP_FORMAT),
  TIKTOK_COOKIE: z.string().default(ENV_DEFAULTS.TIKTOK_COOKIE),
  FFMPEG_BINARY: z.string().default(ENV_DEFAULTS.FFMPEG_BINARY),
  FFPROBE_BINARY: z.string().default(ENV_DEFAULTS.FFPROBE_BINARY),
});

export type RuntimeConfig = z.infer<typeof runtimeConfigSchema>;
