export const LOG_LEVELS = ['info', 'debug', 'error', 'silent', 'warning'] as const;
export const MEDIA_VIDEO_ENCODERS = ['auto', 'libx264', 'h264_nvenc'] as const;

export const ENV_DEFAULTS = {
  NODE_ENV: 'development',
  LOG: 'info',
  PORT: 3000,
  I18N: 'fr',
  ADMIN_UI_TOKEN: '',
  ADMIN_UI_LOCAL_ONLY: true,
  INGEST_API_TOKEN: '',
  HIDE_COMMANDS_DISABLED: 'false',
  DEFAULT_DURATION: 5,
  PLAYBACK_JOB_RETENTION_HOURS: 72,
  MEDIA_STORAGE_DIR: './data/media',
  MEDIA_CACHE_TTL_HOURS: 12,
  MEDIA_CACHE_MAX_TOTAL_MB: 5120,
  MEDIA_BOARD_MAX_TOTAL_MB: 15360,
  MEDIA_DOWNLOAD_TIMEOUT_MS: 180000,
  MEDIA_MAX_SIZE_MB: 2048,
  MEDIA_VIDEO_MAX_HEIGHT: 1080,
  MEDIA_VIDEO_ENCODER: 'auto',
  MEDIA_VIDEO_NVENC_PRESET: 'p4',
  MEDIA_VIDEO_PRESET: 'ultrafast',
  MEDIA_AUDIO_NORMALIZE_ENABLED: true,
  MEDIA_AUDIO_LOUDNORM_I: -18,
  MEDIA_AUDIO_LOUDNORM_LRA: 11,
  MEDIA_AUDIO_LOUDNORM_TP: -1.5,
  TWITTER_OEMBED_ENDPOINT: 'https://publish.twitter.com/oembed',
  TWITTER_VIDEO_RESOLVER_BASE_URL: 'https://vxtwitter.com',
  TWITTER_CARD_DURATION_SEC: 15,
  PAIRING_CODE_TTL_MINUTES: 5,
  YTDLP_BINARY: 'yt-dlp',
  YTDLP_CONCURRENT_FRAGMENTS: 1,
  YTDLP_FORMAT:
    'bv*[vcodec^=avc1][ext=mp4][height<=1080]+ba[ext=m4a]/b[vcodec^=avc1][ext=mp4][height<=1080]/bv*[ext=mp4][height<=1080]+ba[ext=m4a]/b[ext=mp4][height<=1080]/bv*[height<=1080]+ba/b[height<=1080]/best',
  TIKTOK_COOKIE: '',
  FFMPEG_BINARY: 'ffmpeg',
  FFPROBE_BINARY: 'ffprobe',
} as const;
